# Базовый образ
FROM node:22.15.0

# Рабочая директория
WORKDIR /app

# Копирование файлов package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование остальных файлов проекта
COPY . .

# Сборка проекта для продакшена
RUN npm run build

# Команда по умолчанию
CMD ["npm", "run", "serve"]
